name: Artifact

on:
  push:
    branches:
      - ci/*

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
        
    - name: Display structure of downloaded files
      run: ls -R
